version: '3.8'

services:
  mozik_web_web:
    build:
      context: .
    container_name: mozik_web
    ports:
      - "80:5000"
    environment:
      - FLASK_APP=app.py
      - FLASK_ENV=production
      - FLASK_DEBUG=0
    restart: unless-stopped
    networks:
      - mozik_network
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:5000/"]
      interval: 10s
      timeout: 10s
      retries: 3
      start_period: 40s

networks:
  mozik_network:
    driver: bridge